### ISSUE TITLE
Build faliure on Fedora 38 with JUCE 7.0.6 and gcc-13.1

### ISSUE THREAD

**Issue by ycollet** [FigBug/Piano#2]
Piano fails to build on Fedora 38 with JUCE 7.0.6.
It looks like a cpp file is missing to build the VST3 plugin.

**Comment by FigBug** [comment]
I switched to cmake and clang, does it build now?

**Comment by ycollet** [comment]
Thanks for this answer. I will do the test this week end !

**Comment by ycollet** [comment]
I tried today and there is an error related to uninitialized variable in the code. I use gcc 13.1 on Fedora 38 and this version of gcc is checking a lot this kind of things ...
```
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<128, 1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<128>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<128>::order [128]'
  821 |     int order[N];
      |         ^~~~~
/tmp/Piano/plugin/Source/fft.h: In instantiation of 'const fft_order<128> fft_reorder<128, -1>::order':
/tmp/Piano/plugin/Source/fft.h:833:24:   required from 'static void fft_reorder<N, dir>::reorder(float (*)[2]) [with int N = 128; int dir = -1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.h:849:32:   required from 'void fft(float (*)[2]) [with int N = 128; int dir = -1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.cpp:10:16:   required from here
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<128, -1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<128>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<128>::order [128]'
  821 |     int order[N];
      |         ^~~~~
/tmp/Piano/plugin/Source/fft.h: In instantiation of 'const fft_order<256> fft_reorder<256, 1>::order':
/tmp/Piano/plugin/Source/fft.h:833:24:   required from 'static void fft_reorder<N, dir>::reorder(float (*)[2]) [with int N = 256; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.h:849:32:   required from 'void fft(float (*)[2]) [with int N = 256; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.cpp:15:15:   required from here
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<256, 1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<256>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<256>::order [256]'
  821 |     int order[N];
      |         ^~~~~
/tmp/Piano/plugin/Source/fft.h: In instantiation of 'const fft_order<256> fft_reorder<256, -1>::order':
/tmp/Piano/plugin/Source/fft.h:833:24:   required from 'static void fft_reorder<N, dir>::reorder(float (*)[2]) [with int N = 256; int dir = -1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.h:849:32:   required from 'void fft(float (*)[2]) [with int N = 256; int dir = -1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.cpp:20:16:   required from here
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<256, -1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<256>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<256>::order [256]'
  821 |     int order[N];
      |         ^~~~~
/tmp/Piano/plugin/Source/fft.h: In instantiation of 'const fft_order<384> fft_reorder<384, 1>::order':
/tmp/Piano/plugin/Source/fft.h:833:24:   required from 'static void fft_reorder<N, dir>::reorder(float (*)[2]) [with int N = 384; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.h:849:32:   required from 'void fft(float (*)[2]) [with int N = 384; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.cpp:25:15:   required from here
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<384, 1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<384>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<384>::order [384]'
  821 |     int order[N];
      |         ^~~~~
/tmp/Piano/plugin/Source/fft.h: In instantiation of 'const fft_order<512> fft_reorder<512, 1>::order':
/tmp/Piano/plugin/Source/fft.h:833:24:   required from 'static void fft_reorder<N, dir>::reorder(float (*)[2]) [with int N = 512; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.h:849:32:   required from 'void fft(float (*)[2]) [with int N = 512; int dir = 1; t_fft = float [2]]'
/tmp/Piano/plugin/Source/fft.cpp:30:15:   required from here
/tmp/Piano/plugin/Source/fft.h:842:20: error: uninitialized 'const fft_reorder<512, 1>::order' [-fpermissive]
  842 | const fft_order<N> fft_reorder<N,dir>::order;
      |                    ^~~~~~~~~~~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:813:7: note: 'const class fft_order<512>' has no user-provided default constructor
  813 | class fft_order {
      |       ^~~~~~~~~
/tmp/Piano/plugin/Source/fft.h:821:9: note: and the implicitly-defined constructor does not initialize 'int fft_order<512>::order [512]'
  821 |     int order[N];
      |         ^~~~~
make[2]: *** [CMakeFiles/Piano.dir/build.make:178: CMakeFiles/Piano.dir/plugin/Source/fft.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:161: CMakeFiles/Piano.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by friedolino78** [comment]
same build error with gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by garrettendi** [comment]
I'm getting the same build failure: elemtary OS 8.

**Comment by knvl98** [comment]
im getting a similar error
gmake[2]: *** [CMakeFiles/Piano.dir/build.make:178: CMakeFiles/Piano.dir/plugin/Source/fft.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/Piano.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
